Grammar
is-a-dev/is-a-dev.github.io pull request #6
Opened 2022-06-16 05:07 UTC by WilliamDavidHarrison

2022-06-16 05:19 UTC, WilliamDavidHarrison commented
@phenax

2022-06-16 09:13 UTC, MaskDuck requested changes

2022-06-16 09:13 UTC, MaskDuck commented on index.html
> +        .
unrelated change?

2022-06-16 09:21 UTC, WilliamDavidHarrison commented on index.html
> +        .
It adds a full stop at the end

2022-06-21 08:50 UTC, phenax approved these changes

2022-06-21 08:51 UTC, merged